/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package kereta;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author rongrong
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        kode = new javax.swing.JComboBox<>();
        harga = new javax.swing.JTextField();
        jumlah = new javax.swing.JTextField();
        kategori = new javax.swing.JTextField();
        tujuan = new javax.swing.JComboBox<>();
        asal = new javax.swing.JComboBox<>();
        nama = new javax.swing.JTextField();
        simpan = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tData = new javax.swing.JTable();
        delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/kereta/kecil.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, -10, 130, 110);

        jLabel2.setFont(new java.awt.Font("Segoe Marker", 1, 36)); // NOI18N
        jLabel2.setText("FORMULIR PEMESANAN TIKET");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(190, 20, 480, 70);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 850, 100);

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));
        jPanel2.setLayout(null);

        kode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kode Kereta", "PD3009", "PD4004", "PD0515", "PD0108" }));
        jPanel2.add(kode);
        kode.setBounds(20, 20, 220, 40);

        harga.setText("Harga");
        harga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hargaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hargaMouseEntered(evt);
            }
        });
        jPanel2.add(harga);
        harga.setBounds(20, 320, 220, 40);

        jumlah.setText("Jumlah Tiket");
        jumlah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jumlahMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jumlahMouseEntered(evt);
            }
        });
        jPanel2.add(jumlah);
        jumlah.setBounds(20, 270, 220, 40);

        kategori.setText("Kategori");
        kategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kategoriMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                kategoriMouseEntered(evt);
            }
        });
        jPanel2.add(kategori);
        kategori.setBounds(20, 220, 220, 40);

        tujuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Stasiun Tujuan", "Kediri", "Tulungagung", "Blitar", "Malang" }));
        jPanel2.add(tujuan);
        tujuan.setBounds(20, 170, 220, 40);

        asal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Stasiun Asal", "Kediri", "Tulungagung", "Blitar", "Malang" }));
        jPanel2.add(asal);
        asal.setBounds(20, 120, 220, 40);

        nama.setText("Nama Pemesan");
        nama.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                namaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                namaMouseEntered(evt);
            }
        });
        jPanel2.add(nama);
        nama.setBounds(20, 70, 220, 40);

        simpan.setFont(new java.awt.Font("Segoe Marker", 1, 18)); // NOI18N
        simpan.setForeground(new java.awt.Color(0, 0, 102));
        simpan.setText("Submit");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        jPanel2.add(simpan);
        simpan.setBounds(20, 410, 100, 40);

        reset.setFont(new java.awt.Font("Segoe Marker", 1, 18)); // NOI18N
        reset.setForeground(new java.awt.Color(0, 0, 102));
        reset.setText("Reset");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });
        jPanel2.add(reset);
        reset.setBounds(140, 410, 100, 40);

        tData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Kode Kereta", "Nama", "Stasiun Asal", "Stasiun Tujuan", "Kategori", "Jumlah", "Harga"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tData);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(260, 20, 580, 380);

        delete.setFont(new java.awt.Font("Segoe Marker", 1, 18)); // NOI18N
        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel2.add(delete);
        delete.setBounds(740, 410, 100, 40);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 110, 850, 490);

        setBounds(0, 0, 866, 639);
    }// </editor-fold>//GEN-END:initComponents

    private void hargaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hargaMouseClicked
        // TODO add your handling code here:
        harga.setText("");
    }//GEN-LAST:event_hargaMouseClicked

    private void hargaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hargaMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_hargaMouseEntered

    private void jumlahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jumlahMouseClicked
        // TODO add your handling code here:
        jumlah.setText("");
    }//GEN-LAST:event_jumlahMouseClicked

    private void jumlahMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jumlahMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_jumlahMouseEntered

    private void kategoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kategoriMouseClicked
        // TODO add your handling code here:
        kategori.setText("");
    }//GEN-LAST:event_kategoriMouseClicked

    private void kategoriMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kategoriMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_kategoriMouseEntered

    private void namaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_namaMouseClicked
        // TODO add your handling code here:
        nama.setText("");
    }//GEN-LAST:event_namaMouseClicked

    private void namaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_namaMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_namaMouseEntered

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        if("".equals(nama.getText()) || "".equals(kategori.getText()) || "".equals(harga.getText())
            || "".equals(jumlah.getText()) || "".equals(kode.getSelectedItem()) || "".equals(asal.getSelectedItem()) || 
                "".equals(tujuan.getSelectedItem()))
        {
            JOptionPane.showMessageDialog(this, "Harap lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        }
        else {
            
            String SQL = "INSERT INTO data_tiket (kode_kereta,nama,stasiun_asal,stasiun_tujuan,ketrgori,jumlah_tiket,harga) "
                    + "VALUES ('"+kode.getSelectedItem()+"', '"+nama.getText()+"', '"+asal.getSelectedItem()+"', '"+
                    tujuan.getSelectedItem()+"', '"+kategori.getText()+"', '"+jumlah.getText()+"', '"+harga.getText()+"')";
            int status = KoneksiDB.execute(SQL);
            if(status == 1){
                JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            }
            else{
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_simpanActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        // TODO add your handling code here:
        nama.setText("");
        kategori.setText("");
        jumlah.setText("");
        harga.setText("");
        kode.setSelectedItem(null);
        tujuan.setSelectedItem(null);
        asal.setSelectedItem(null);
    }//GEN-LAST:event_resetActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> asal;
    private javax.swing.JButton delete;
    private javax.swing.JTextField harga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlah;
    private javax.swing.JTextField kategori;
    private javax.swing.JComboBox<String> kode;
    private javax.swing.JTextField nama;
    private javax.swing.JButton reset;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tData;
    private javax.swing.JComboBox<String> tujuan;
    // End of variables declaration//GEN-END:variables

private void selectData() {
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        String kolom[]= {"kode_kereta","nama","stasiun_asal","stasiun_tujuan","ketrgori","jumlah_tiket","harga"};
         DefaultTableModel dtm = new DefaultTableModel(null, kolom);
         String SQL = "SELECT * FROM data_tiket";
         ResultSet rs = KoneksiDB.executeQuery(SQL);
         try{
             while(rs.next()){
                 String kode = rs.getString(1);
                 String nama = rs.getString(2);
                 String asal = rs.getString(3);
                 String tujuan =rs.getString(4);
                 String kategori = rs.getString(5);
                 String jumlah = rs.getString(6);
                 String harga = rs.getString(7);
                 String data[]= {kode,nama,asal,tujuan,kategori,jumlah,harga};
                 dtm.addRow(data);
             }
         }catch(SQLException ex){
             Logger.getLogger(home.class.getName()).log(Level.SEVERE, null, ex);
         }
         tData.setModel(dtm);
    }
}
